name: CI to Dockerhub
on:
  push:
    branches: test
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2  
      -
        uses: actions/setup-python@v1
      - uses: BSFishy/pip-action@v1
        with:
          upgrade: true
          requirements: 'requirements.txt'
      - run: python bot.py ${{ secrets.TELEGRAM_TOKEN }} ${{ secrets.TELEGRAM_CHAT_ID }} true  
      - run: echo "Succesfully test." 
