name: CI to Dockerhub
on:
  push:
    branches: main
    
jobs:
  main:
    env:
      repoName: emaxx21/telegrambot
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout  
        uses: actions/checkout@v2   
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: calculate next version
        id: version
        uses: patrickjahns/version-drafter-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          #context: .
          file: ./Dockerfile
          push: true
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          tags: |
            ${{ env.repoName }}:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
        
      - 
        name: New Version
        run: echo Next:${{ steps.version.outputs.next-version }}
        run: echo Current:${{ steps.version.outputs.current-version }} 
