name: CI to Dockerhub
on:
  push:
    branches: main
    
jobs:
  main:
    env:
      repoName: emaxx21/telegrambot
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Version management
        uses: PssbleTrngle/VersionManagment@v1.0.8
        id: Version
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fallback: v0.1.0
          prefix: v
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          #context: .
          file: ./Dockerfile
          push: true
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          tags: |
            ${{ env.repoName }}:latest
            ${{ env.repoName }}:${{ steps.version.outputs.next }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
        
      - 
        name: New Version
        run: echo ${{ steps.version.outputs.next }}
