name: CI to Dockerhub
on:
  push:
    branches: main
jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      repoName: emaxx21/telegrambot
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        id: release
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: minor

      - 
        name: Check Output Parameters
        run: |
          echo "New tag name ${{ steps.release.outputs.tag_name }}"
          echo "New release version ${{ steps.release.outputs.version }}"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          #context: .
          file: ./Dockerfile
          push: true
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          tags: |
            ${{ env.repoName }}:latest
            ${{ env.repoName }}:${{ steps.release.outputs.tag_name }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
