name: Test and verify
on:
  push:
    branches: test
jobs:
  run-and-test:
    runs-on: ubuntu-latest
  steps:
  - uses: actions/setup-python@v2
  with:
    python-version: '3.8'
    architecture: 'x64' 
  - run: |
        python pip install --upgrade TelegramBotInterface
        python bot.py ${{ secrets.TOKEN }} ${{ secrets.CHAT_ID }} --test