name: Test and verify
on:
  push:
    branches: test
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: BSFishy/pip-action@v1
      with:
        packages: |
          TelegramBotInterface
    - run: python bot.py ${{ secrets.TOKEN }} ${{ secrets.CHAT_ID }} --test 
    - uses: actions/setup-python@v2
      with:
        python-version: '3.7'
        architecture: 'x64'
    - run: python bot.py ${{ secrets.TOKEN }} ${{ secrets.CHAT_ID }} --test
